apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SKSC/argocd-install.git
    targetRevision: feature/test
    path: chart/argo-cd
    helm:
      valueFiles:
        - ../../values/common.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd


  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true