---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'nginx-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://charts.bitnami.com/bitnami'
        chart: nginx
        targetRevision: 18.2.1
        helm:
          parameters:
            - name: installCRDs
              value: "true"
      destination:
        server: "{{server}}"
        namespace: nginx
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - Prune=true
        automated:
          prune: true
          selfHeal: true