---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'cert-manager-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://charts.jetstack.io'
        chart: cert-manager
        targetRevision: v1.6.1
        helm:
          parameters:
            - name: installCRDs
              value: "true"
      destination:
        server: "{{server}}"
        namespace: cert-manager
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
